services:
  web:
    build: .
    command: make run
    volumes:
        - /var/esign/logs:/app/logs
        - /var/esign/media:/app/media
        - /var/esign/database:/app/db
    ports:
        - "${DEPLOYMENT_PORT:-8082}:8000"
    environment:
        - PYTHONDONTWRITEBYTECODE=1
        - PYTHONUNBUFFERED=1